title: Learning Julia
author: Michele Pratusevich
email: mail@learningjulia.com
description: > 
  A blog documenting my learning of the Julia programming
  language. My background is in computer vision and computational
  photography, so the posts and projects will have a vision-and-graphics
  bent.
baseurl: ""
url: "https://learningjulia.com"
twitter:
  username: learningjulia
github:
  username:  mprat
google_analytics: G-E8SQHHCGTK
disqus:
  shortname: learningjulia
logo: /assets/imgs/learningjulia.svg
social:
  links:
    - https://twitter.com/learningjulia

# Build settings
safe: true
markdown: kramdown
highlighter: rouge
theme: minima
plugins:
  - jekyll-feed
  - jekyll-coffeescript
  - jekyll-gist
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
whitelist:
  - jekyll-coffeescript
  - jekyll-gist
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-redirect-from

kramdown:
  input: GFM
  hard_wrap: false

excerpt_separator: <!--more-->

# default image for twitter cards
# and facebook open-graph
defaults:
  - scope:
      path: ""
    values:
      image: /assets/imgs/learningjulia.svg
      height: 250
      width: 250
