title: Learning Julia
author:
  name: Michele Pratusevich
  email: mail@learningjulia.com
description: > 
  A blog documenting my learning of the Julia programming
  language. My background is in computer vision and computational
  photography, so the posts and projects will have a vision-and-graphics
  bent.
baseurl: ""
url: "http://learningjulia.com"
twitter_username: learningjulia
github_username:  mprat
google_analytics: UA-44633314-3

# Build settings
safe: true
markdown: kramdown
highlighter: rouge
theme: minima
gems:
  - jekyll-feed
  - jekyll-coffeescript
  - jekyll-gist
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-redirect-from
exclude:
  - Gemfile
  - Gemfile.lock
whitelist:
  - jekyll-coffeescript
  - jekyll-gist
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-redirect-from

kramdown:
  input: GFM
  hard_wrap: false

excerpt_separator: <!--more-->